export const GET_PROJECT_DATA = 'GET_PROJECT_DATA';
export const GET_PROJECT_DATA_FULFILLED = 'GET_PROJECT_DATA_FULFILLED';
export const GET_PROJECT_DATA_PENDING = 'GET_PROJECT_DATA_PENDING';
export const GET_PROJECT_DATA_REJECTED = 'GET_PROJECT_DATA_REJECTED';
export const GET_MESSAGES = 'GET_MESSAGES';
export const GET_MESSAGES_FULFILLED = 'GET_MESSAGES_FULFILLED';
export const GET_MESSAGES_PENDING = 'GET_MESSAGES_PENDING';
export const GET_MESSAGES_REJECTED = 'GET_MESSAGES_REJECTED';
